version: '3.7'
services:
    django:
      restart: always
      build:
        context: .
      ports:
        - 8000:8000
      container_name: restfullapi
      volumes:
        - .:/usr/src/app
      
      command: >
        sh -c "python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"
      
      

